### PR TITLE
Ahmed fathi shaban 20 create destroy group

### PR DESCRIPTION
**Pull request by AhmedFathiShaban**

### CODE REVIEW

**Comment by AhmedFathiShaban** [comment]
@Youssef-Emad

**Comment by AhmedFathiShaban** [comment]
@Youssef-Emad

**Comment by AhmedFathiShaban** [comment]
@Youssef-Emad  @Youssef-Emad  @Youssef-Emad

**Comment by youssef-emad** [comment]
@AhmedFathiShaban 
Good job :smile:

**Pull request merged**
